### ISSUE TITLE
CoAP RTT Increased

### ISSUE THREAD

**Issue by IrfanMeo** [kaleemullah360/kontiki#1]
After last update i.e 21/06/2016 CoAP RTT increased from 40 to 944

**Comment by IrfanMeo** [comment]
CoAP mote hang problem

**Comment by kaleemullah360** [comment]
Increase in RTT is connectivity issue. check if you're receiving random values. if so then change channel & TX value.

for CoAP app, if hanged check it with Copper plugin. decrease the `#define sampleNo 41` and check if problem exist. if problem still exist than it might be connectivity issue.
